version: 2

project_name: mishmesh

builds:
  - id: server
    main: ./cmd/mishmesh-server
    binary: mishmesh-server
    env: [CGO_ENABLED=0]
    flags: [-trimpath]
    ldflags: ["-s -w -X main.version={{ .Tag }}"]
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
  - id: agent
    main: ./cmd/mishmesh-agent
    binary: mishmesh-agent
    env: [CGO_ENABLED=0]
    flags: [-trimpath]
    ldflags: ["-s -w -X main.version={{ .Tag }}"]
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]

archives:
  - id: server
    ids: [server]
    name_template: "mishmesh-server_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    files: [LICENSE, README.md, CHANGELOG.md]
  - id: agent
    ids: [agent]
    name_template: "mishmesh-agent_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    files: [LICENSE, CHANGELOG.md, deploy/examples/agent.yml]

checksum:
  name_template: checksums.txt
  extra_files:
    - glob: ./dist-web/mishmesh-webui_*.tar.gz

release:
  prerelease: auto
  extra_files:
    - glob: ./dist-web/mishmesh-webui_*.tar.gz

changelog:
  disable: true
