{{- $tunnelTokens := list -}}
{{- range .Values.tunnels -}}
{{- if and .token (not .existingSecret) -}}
{{- $tunnelTokens = append $tunnelTokens . -}}
{{- end -}}
{{- end -}}
{{- if or (and .Values.token (not .Values.existingSecret)) $tunnelTokens }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mishmesh-agent.fullname" . }}
  labels:
    {{- include "mishmesh-agent.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if and .Values.token (not .Values.existingSecret) }}
  token: {{ .Values.token | b64enc | quote }}
  {{- end }}
  {{- range $tunnelTokens }}
  token-{{ .name }}: {{ .token | b64enc | quote }}
  {{- end }}
{{- end }}
