{{- if .Values.service.public.enabled }}
{{- $v := .Values }}
{{- $svc := $v.service.public }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mishmesh.fullname" . }}-public
  labels:
    {{- include "mishmesh.labels" . | nindent 4 }}
    {{- with $svc.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $svc.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ $svc.type }}
  {{- if or (eq $svc.type "LoadBalancer") (eq $svc.type "NodePort") }}
  externalTrafficPolicy: {{ $svc.externalTrafficPolicy }}
  {{- end }}
  {{- if eq $svc.type "LoadBalancer" }}
  {{- with $svc.loadBalancerClass }}
  loadBalancerClass: {{ . }}
  {{- end }}
  {{- with $svc.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with $svc.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  selector:
    {{- include "mishmesh.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ $v.listeners.http.servicePort }}
      targetPort: {{ $v.listeners.http.containerPort }}
      protocol: TCP
    {{- if $v.listeners.https.enabled }}
    - name: https
      port: {{ $v.listeners.https.servicePort }}
      targetPort: {{ $v.listeners.https.containerPort }}
      protocol: TCP
    {{- end }}
    {{- if $v.listeners.tlsPassthrough.enabled }}
    - name: tls-passthrough
      port: {{ $v.listeners.tlsPassthrough.servicePort }}
      targetPort: {{ $v.listeners.tlsPassthrough.containerPort }}
      protocol: TCP
    {{- end }}
    {{- if $v.listeners.ssh.enabled }}
    - name: ssh
      port: {{ $v.listeners.ssh.servicePort }}
      targetPort: {{ $v.listeners.ssh.containerPort }}
      protocol: TCP
    {{- end }}
    {{- range $p := include "mishmesh.tcpPorts" . | fromJsonArray }}
    - name: tcp-{{ int $p }}
      port: {{ int $p }}
      targetPort: {{ int $p }}
      protocol: TCP
    {{- end }}
{{- end }}
