apiVersion: v1
kind: Service
metadata:
  name: {{ include "mishmesh.fullname" . }}-api
  labels:
    {{- include "mishmesh.labels" . | nindent 4 }}
    app.kubernetes.io/service: api
    {{- with .Values.service.api.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.api.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.api.type }}
  selector:
    {{- include "mishmesh.selectorLabels" . | nindent 4 }}
  ports:
    - name: api
      port: {{ .Values.listeners.api.servicePort }}
      targetPort: api
      protocol: TCP
{{- if .Values.ingress.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mishmesh.fullname" . }}-http
  labels:
    {{- include "mishmesh.labels" . | nindent 4 }}
    app.kubernetes.io/service: http
spec:
  type: ClusterIP
  selector:
    {{- include "mishmesh.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
{{- end }}
